<h1 style="font-size:40px;"> MLlib: Machine Learning con Spark </h1>

In [1]:
import numpy as np
import pyspark.sql.functions as F
from pyspark import SparkConf
from pyspark.ml import Pipeline
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.ml.feature import VectorAssembler, VectorIndexer
from pyspark.ml.regression import DecisionTreeRegressor, RandomForestRegressor
from pyspark.sql import SparkSession

In [2]:
conf = (
    SparkConf()
    .setAppName("[ICAI] ML a fondo")
    .set("spark.executor.memory", "7g")
    .set("spark.executor.cores", "5")
    .set("spark.default.parallelism", 800)
    .set("spark.sql.shuffle.partitions", 800)
)

In [3]:
spark = SparkSession.builder.config(conf=conf).enableHiveSupport().getOrCreate()

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

In [4]:
spark.sparkContext.setLogLevel("FATAL")

# Tuning de modelos

![](img/rf.jpg)

Como hemos visto en el ejercicio anterior estabamos consiguiendo peores resultados en el [Random Forest](https://es.wikipedia.org/wiki/Random_forest) que un solo árbol, veamos como solucionar esto:

In [5]:
trainDF, testDF = (
    spark.read.options(header=True, inferSchema=True)
    .csv("/datos/hour.csv")
    .drop("casual", "registerd", "instant", "dteday")
    .randomSplit([0.7, 0.3], seed=1234)
)

In [6]:
trainDF.cache()
testDF.cache()
print("## Número de registros en `trainDF`: {}".format(trainDF.count()))
print("## Número de registros en `testDF`: {}".format(testDF.count()))

## Número de registros en `trainDF`: 12201
## Número de registros en `testDF`: 5178

In [7]:
featuresCols = trainDF.columns[:-1]
featuresCols

['season',
 'yr',
 'mnth',
 'hr',
 'holiday',
 'weekday',
 'workingday',
 'weathersit',
 'temp',
 'atemp',
 'hum',
 'windspeed',
 'registered']

#### Primero montamos de nuevo el árbol:

In [8]:
vectorAssembler = VectorAssembler(inputCols=featuresCols, outputCol="rawFeatures")

In [9]:
vectorIndexer = VectorIndexer(inputCol="rawFeatures", outputCol="features")

In [10]:
dt = DecisionTreeRegressor(labelCol="cnt")

In [11]:
pipeline = Pipeline(stages=[vectorAssembler, vectorIndexer, dt])

In [12]:
model = pipeline.fit(trainDF)

In [13]:
evaluator = RegressionEvaluator(labelCol="cnt")

In [14]:
rmse_train = evaluator.evaluate(model.transform(trainDF))
rmse_valid = evaluator.evaluate(model.transform(testDF))

In [15]:
print("## RMSE (Train): {:.3f}".format(rmse_train))
print("## RMSE (Valid): {:.3f}".format(rmse_valid))

## RMSE (Train): 32.151
## RMSE (Valid): 33.357

#### Ahora el bosque:

In [16]:
rf = RandomForestRegressor(labelCol="cnt")

In [17]:
pipeline2 = Pipeline(stages=model.stages[:-1] + [rf])

In [18]:
model2 = pipeline2.fit(trainDF)

In [19]:
rmse_train = evaluator.evaluate(model2.transform(trainDF))
rmse_valid = evaluator.evaluate(model2.transform(testDF))

In [20]:
print("## RMSE (Train): {:.3f}".format(rmse_train))
print("## RMSE (Valid): {:.3f}".format(rmse_valid))

## RMSE (Train): 42.501
## RMSE (Valid): 42.884

Los modelos más complejos tienen varios hiper-parámetros que hay que configurar para conseguir la mayor *performance*, a esta búsqueda de la configuración óptima se le suele conocer como [*tuning*](https://en.wikipedia.org/wiki/Hyperparameter_optimization). Veamos los parámetros del modelo en cuestión:

In [21]:
print(RandomForestRegressor().explainParams())

bootstrap: Whether bootstrap samples are used when building trees. (default: True)
cacheNodeIds: If false, the algorithm will pass trees to executors to match instances with nodes. If true, the algorithm will cache node IDs for each instance. Caching can speed up training of deeper trees. Users can set how often should the cache be checkpointed or disable it by setting checkpointInterval. (default: False)
checkpointInterval: set checkpoint interval (>= 1) or disable checkpoint (-1). E.g. 10 means that the cache will get checkpointed every 10 iterations. Note: this setting will be ignored if the checkpoint directory is not set in the SparkContext. (default: 10)
featureSubsetStrategy: The number of features to consider for splits at each tree node. Supported options: 'auto' (choose automatically for task: If numTrees == 1, set to 'all'. If numTrees > 1 (forest), set to 'sqrt' for classification and to 'onethird' for regression), 'all' (use all features), 'onethird' (use 1/3 of the features), 'sqrt' (use sqrt(number of features)), 'log2' (use log2(number of features)), 'n' (when n is in the range (0, 1.0], use n * number of features. When n is in the range (1, number of features), use n features). default = 'auto' (default: auto)
featuresCol: features column name. (default: features)
impurity: Criterion used for information gain calculation (case-insensitive). Supported options: variance (default: variance)
labelCol: label column name. (default: label)
leafCol: Leaf indices column name. Predicted leaf index of each instance in each tree by preorder. (default: )
maxBins: Max number of bins for discretizing continuous features.  Must be >=2 and >= number of categories for any categorical feature. (default: 32)
maxDepth: Maximum depth of the tree. (>= 0) E.g., depth 0 means 1 leaf node; depth 1 means 1 internal node + 2 leaf nodes. Must be in range [0, 30]. (default: 5)
maxMemoryInMB: Maximum memory in MB allocated to histogram aggregation. If too small, then 1 node will be split per iteration, and its aggregates may exceed this size. (default: 256)
minInfoGain: Minimum information gain for a split to be considered at a tree node. (default: 0.0)
minInstancesPerNode: Minimum number of instances each child must have after split. If a split causes the left or right child to have fewer than minInstancesPerNode, the split will be discarded as invalid. Should be >= 1. (default: 1)
minWeightFractionPerNode: Minimum fraction of the weighted sample count that each child must have after split. If a split causes the fraction of the total weight in the left or right child to be less than minWeightFractionPerNode, the split will be discarded as invalid. Should be in interval [0.0, 0.5). (default: 0.0)
numTrees: Number of trees to train (>= 1). (default: 20)
predictionCol: prediction column name. (default: prediction)
seed: random seed. (default: 7562011667716574274)
subsamplingRate: Fraction of the training data used for learning each decision tree, in range (0, 1]. (default: 1.0)
weightCol: weight column name. If this is not set or empty, we treat all instance weights as 1.0. (undefined)

In [22]:
rf3 = RandomForestRegressor(labelCol="cnt", numTrees=200, maxDepth=10)

In [23]:
model3 = Pipeline(stages=model.stages[:-1] + [rf3]).fit(trainDF)

In [24]:
rmse_train = evaluator.evaluate(model3.transform(trainDF))
rmse_valid = evaluator.evaluate(model3.transform(testDF))

In [25]:
print("## RMSE (Train): {:.3f}".format(rmse_train))
print("## RMSE (Valid): {:.3f}".format(rmse_valid))

## RMSE (Train): 17.991
## RMSE (Valid): 21.579

¡Ya hemos conseguido mejores resultados!

### Cross-validation y búsqueda por malla

![](img/cv.png)

En Spark MLlib existen funciones para hacer fácil la búsqueda de hiperparámetros y la [validación cruzada](https://en.wikipedia.org/wiki/Cross-validation_(statistics))

In [26]:
from pyspark.ml.tuning import CrossValidator, ParamGridBuilder

In [27]:
paramGrid = (
    ParamGridBuilder().addGrid(rf.numTrees, [100, 200, 300]).addGrid(rf.maxDepth, [4, 10]).build()
)

In [28]:
crossval = CrossValidator(
    estimator=pipeline2, estimatorParamMaps=paramGrid, evaluator=evaluator, numFolds=3
)

**CUIDADO** Este `fit` puede durar varios minutos:

In [29]:
cvModel = crossval.fit(trainDF)

In [30]:
cvModel.avgMetrics

[52.665875244066655,
 22.984465213175763,
 52.61428835803573,
 22.96541831829431,
 51.55209794322068,
 22.83834880137572]

In [31]:
mejor = np.argsort(cvModel.avgMetrics)[0]

In [32]:
mejor

5

In [33]:
cvModel.avgMetrics[mejor]

22.83834880137572

In [34]:
cvModel.getEstimatorParamMaps()[mejor]

{Param(parent='RandomForestRegressor_d22c4e96536d', name='numTrees', doc='Number of trees to train (>= 1).'): 300,
 Param(parent='RandomForestRegressor_d22c4e96536d', name='maxDepth', doc='Maximum depth of the tree. (>= 0) E.g., depth 0 means 1 leaf node; depth 1 means 1 internal node + 2 leaf nodes. Must be in range [0, 30].'): 10}

In [35]:
rmse_train = evaluator.evaluate(cvModel.transform(trainDF))
rmse_valid = evaluator.evaluate(cvModel.transform(testDF))

In [36]:
print("## RMSE (Train): {:.3f}".format(rmse_train))
print("## RMSE (Valid): {:.3f}".format(rmse_valid))

## RMSE (Train): 17.801
## RMSE (Valid): 21.457

# Clustering: K-Means

![](img/wikimedia.png)

Veamos un ejemplo de modelo no supervisado. Usaremos para ello un dataset de artículos de wikipedia que se puede encontrar en: https://dumps.wikimedia.org/

In [37]:
wiki_df = spark.read.parquet("/datos/wiki.parquet").repartition(800).cache()

In [38]:
wiki_df.count()

111495

In [39]:
wiki_df.printSchema()

root
 |-- id: long (nullable = true)
 |-- title: string (nullable = true)
 |-- lastrev_pdt_time: timestamp (nullable = true)
 |-- revid: long (nullable = true)
 |-- comment: string (nullable = true)
 |-- contributorid: long (nullable = true)
 |-- contributorusername: string (nullable = true)
 |-- contributorip: string (nullable = true)
 |-- text: string (nullable = true)

In [40]:
wiki_df.limit(10).toPandas()

/opt/share/anaconda/lib/python3.11/site-packages/pyspark/sql/pandas/conversion.py:251: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

,id,title,lastrev_pdt_time,revid,comment,contributorid,contributorusername,contributorip,text
0,7523301,Syrian Premier League,2016-03-04 16:29:02,708327892,Removed image per [[Wikipedia:Files for discus...,4842600.0,Explicit,None,{{Infobox football league\n| logo = \n| ...
1,503927,Parachutes (album),2016-03-03 09:33:52,708097430,/* Critical reception */ Replacing user review,4279454.0,Holiday56,None,{{EngvarB|date=September 2013}}\n{{Use dmy dat...
2,12418406,Vinous-breasted sparrowhawk,2016-03-04 16:52:23,708330760,Accipitriformes-stub,730134.0,Pelagic,None,{{Taxobox\n| name = Vinous-breasted sparrowhaw...
3,41099217,"Newcastle upon Tyne West by-election, 1940",2016-03-04 15:26:30,708319709,Whoever wrote this originally should be shot,13249188.0,Marplesmustgo,None,The '''[[Newcastle upon Tyne West (UK Parliame...
4,6024369,Tim Stoddard,2016-03-04 11:07:24,708281097,migrating [[Wikipedia:Persondata|Persondata]] ...,24420788.0,KasparBot,None,{{BLP sources|date=January 2008}}\n{{Infobox b...
5,8040205,"O come, O come, Emmanuel",2016-03-03 01:06:52,708044902,"/* Text */ Restored ""are essentially the same ...",3784662.0,Liberalartist,None,"'''''O come, O come, Emmanuel''''' is a [[Chri..."
6,5870652,Sal Butera,2016-03-03 19:33:26,708177575,migrating [[Wikipedia:Persondata|Persondata]] ...,24420788.0,KasparBot,None,{{Use mdy dates|date=July 2014}}\n{{Infobox ba...
7,6189968,Jake Gibbs,2016-03-05 05:05:27,708407091,migrating [[Wikipedia:Persondata|Persondata]] ...,24420788.0,KasparBot,None,{{Infobox baseball biography\n|name=Jake Gibbs...
8,16341,John Paul Jones,2016-03-04 15:24:45,708319501,Reverted edits by [[Special:Contributions/205....,25523690.0,CAPTAIN RAJU,None,{{about||the Led Zeppelin musician|John Paul J...
9,136920,"Medford, New Jersey",2016-03-03 12:19:10,708119678,There are two area codes,NaN,None,2600:1002:B122:D438:7DB3:73D3:A6F9:B52A,{{Infobox settlement\n| name ...

Empezamos por un tratemiento del texto como ya hemos visto:

In [41]:
for i in wiki_df.select("text").take(4):
    print(i.text)
    print("------------\n\n")

{{Infobox football league
| logo       =
| pixels     =
| country    = Syria
| confed     = AFC
| founded    = 1966
| teams      = 20
| relegation = 2. Syrian League
| levels     = 1
| domest_cup = [[Syrian Cup]]<br />[[Syrian Super Cup]]
| confed_cup = [[AFC Cup]]<br />[[Arab Champions League]]
| champions  = [[Al-Jaish SC (Damascus)|Al-Jaish]]
| season     =  2014???15
| most successful club = [[Al-Jaish SC (Damascus)|Al-Jaish]] (13 titles)
| website    =
| current    = [[2015???16 Syrian Premier League]]
}}

The '''Syrian League''' is the highest division in [[Association football|football]] in [[Syria]]. The league began to play in 1966.

==Current clubs (2015???16)==
===Group 1===
*[[Al-Hurriya SC|Al-Hurriya]] (Aleppo)
*[[Al-Jaish SC (Damascus)|Al-Jaish]] (Damascus)
*[[Al-Jazeera SC Hasakah|Al-Jazeera]]  (Hasakah)
*[[Al-Karamah SC|Al-Karamah]] (Homs)
*[[Al-Majd SC|Al-Majd]] (Damascus)
*[[Al-Muhafaza SC|Al-Muhafaza]] (Damascus)
*[[Taliya SC|Al-Taliya]] (Hama)
*[[Hutteen SC|Hutteen]]  (Latakia)
*[[Jableh SC|Jableh]]  (Jableh)
*[[Omayya SC|Omayya]]  (Idlib)
===Group 2===
*[[Al-Ittihad SC Aleppo|Al-Ittihad]] (Aleppo)
*[[Al-Fotuwa SC|Al-Futowa]] (Deir ez-Zor)
*[[Al-Jihad SC|Al-Jihad]] ''(Relegated)'' (Qamishli)
*[[Nawair SC|Al-Nawair]] (Hama)
*[[Nidal SC|Al-Nidal]] (Damascus)
*[[Al Shorta SC (Damascus)|Al-Shorta]] (Damascus)
*[[Al-Wahda SC Damascus|Al-Wahda]] (Damascus)
*[[Al-Wathba SC|Al-Wathba]] (Homs)
*[[Baniyas Refinery SC|Musfat Baniyas]] (Baniyas)
*[[Tishreen SC|Tishreen]] (Latakia)

==List of champions==
Champions so far are:<ref>{{cite web|url=http://www.rsssf.com/tabless/syrchamp.html|publisher=RSSSF|accessdate=6 July 2012|title=Syria - List of Champions}}</ref>

{| class="wikitable" style="width:55%;"
!style="width:10%;" |Season
!style="width:15%;"|Winner
!style="width:15%;"|Runner-up
!style="width:15%;"|Third Place
|-
|1966???67
|[[Al-Ittihad SC Aleppo|Al-Ittihad]]
|
|
|-
|1967???68
|[[Al-Ittihad SC Aleppo|Al-Ittihad]]
|
|
|-
|1968???69
|[[Barada SC|Barada]]
|
|
|-
|1969???70
|[[Barada SC|Barada]]
|
|
|-
|1970???71
|colspan=3 style=background:#efefef|<center>''No Championship''
|-
|1971???72
|colspan=3 style=background:#efefef|<center>''No Championship''
|-
|1972???73
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|
|
|-
|1973???74
|colspan=3 style=background:#efefef|<center>''No Championship''
|-
|1974???75
|[[Al-Karamah SC|Al-Karamah]]
|
|
|-
|1975???76
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|
|
|-
|1976???77
|[[Al-Ittihad SC Aleppo|Al-Ittihad]]
|
|
|-
|1977???78
|colspan=3 style=background:#efefef|<center>''No Championship''
|-
|1978???79
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|
|
|-
|1979???80
|[[Al Shorta SC (Damascus)|Al-Shorta]]
|
|
|-
|1980???81
|colspan=3 style=background:#efefef|<center>''No Championship''
|-
|1981???82
|[[Tishreen SC|Tishreen]]
|
|
|-
|1982???83
|[[Al-Karamah SC|Al-Karamah]]
|
|
|-
|1983???84
|[[Al-Karamah SC|Al-Karamah]]
|
|
|-
|1984???85
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|
|
|-
|1985???86
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|
|
|-
|1986???87
|[[Jableh SC|Jableh]]
|
|
|-
|1987???88
|[[Jableh SC|Jableh]]
|
|
|-
|1988???89
|[[Jableh SC|Jableh]]
|
|
|-
|1989???90
|[[Al-Fotuwa SC|Al-Futowa]]
|
|
|-
|1990???91
|[[Al-Fotuwa SC|Al-Futowa]]
|
|
|-
|1991???92
|[[Hurriya SC|Hurriya]]
|
|
|-
|1992???93
|[[Al-Ittihad SC Aleppo|Al-Ittihad]]
|
|
|-
|1993???94
|[[Hurriya SC|Hurriya]]
|
|
|-
|1994???95
|[[Al-Ittihad SC Aleppo|Al-Ittihad]]
|
|
|-
|1995???96
|[[Al-Karamah SC|Al-Karamah]]
|
|
|-
|1996???97
|[[Tishreen SC|Tishreen]]
|
|
|-
|1997???98
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|
|
|-
|1998???99
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|
|
|-
|1999???00
|[[Jableh SC|Jableh]]
|
|
|-
|2000???01
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|
|
|-
|2001???02
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|
|
|-
|2002???03
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|
|
|-
|2003???04
|[[Al-Wahda SC Damascus|Al-Wahda]]
|
|
|-
|2004???05
|[[Al-Ittihad SC Aleppo|Al-Ittihad]]
|
|
|-
|2005???06
|[[Al-Karamah SC|Al-Karamah]]
|
|
|-
|2006???07
|[[Al-Karamah SC|Al-Karamah]]
|
|
|-
|[[2007???08 Syrian Premier League|2007???08]]
|[[Al-Karamah SC|Al-Karamah]]
|
|
|-
|[[2008???09 Syrian Premier League|2008???09]]
|[[Al-Karamah SC|Al-Karamah]]
|
|
|-
|[[2009???10 Syrian Premier League|2009???10]]
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|
|
|-
|[[2010???11 Syrian Premier League|2010???11]]
|colspan=3 style=background:#efefef|<center>''Suspended''
|-
|[[2011???12 Syrian Premier League|2011???12]]
|[[Al Shorta SC (Damascus)|Al-Shorta]]
|
|
|-
|[[2013 Syrian Premier League|2013]]
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|
|
|-
|[[2014 Syrian Premier League|2014]]
|[[Al-Wahda SC Damascus|Al-Wahda]]
|
|
|-
|[[2014???15 Syrian Premier League|2014???15]]
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|
|
|}

==Performances==
===Performance by club===
{| class="wikitable sortable" style="width:100%;"
|-
! style="width:15%;"| Club
! style="width:10%;"| Winners
! style="width:10%;"| Runners-up
! style="width:10%;"| Third place
! style="width:55%;"| Winning years
|-
|[[Al-Jaish SC (Damascus)|Al-Jaish]]
|<center>13
|<center>4
|<center>1
|
|-
|[[Al-Karamah SC|Al-Karamah]]
|<center>8
|<center>11
|<center>4
|
|-
|[[Al-Ittihad SC Aleppo|Al-Ittihad]]
|<center>6
|<center>6
|<center>12
|
|-
|[[Jableh SC|Jableh]]
|<center>4
|<center>6
|<center>1
|
|-
|[[Al Shorta SC (Damascus)|Al-Shorta]]
|<center>2
|<center>6
|<center>2
|
|-
|[[Al-Fotuwa SC|Al-Futowa]]
|<center>2
|<center>5
|<center>3
|
|-
|[[Hurriya SC|Al-Hurriya]]
|<center>2
|<center>1
|<center>3
|
|-
|[[Al-Wahda SC Damascus|Al-Wahda]]
|<center>2
|<center>???
|<center>5
|
|-
|[[Tishreen SC|Tishreen]]
|<center>2
|<center>???
|<center>4
|
|-
|[[Barada SC|Barada]]
|<center>2
|<center>???
|<center>2
|
|}

===Performance by city===
{| class="wikitable sortable"
|-
!width="120"| [[List of cities in Syria|City]]
!width="10" | Winners
!width="150"| Club(s)
|-
|
|
|
|-
|
|
|
|-
|
|
|
|-
|
|
|
|-
|
|
|
|-
|
|
|
|-
|
|
|
|}

==See also==
*[[Syrian Premier League top scorers]]

==References==
{{reflist}}

== External links ==
* [http://www.fifa.com/associations/association=syr/nationalleague/standings.html League] at FIFA
* [http://www.soccerway.com/national/syria/ League] at soccerway.com
* [http://hailoosport.com/league?lang=ar&comp_id=640f6eec53e8b4e3381f1f3a10a902dc Syrian Premier League - Hailoosport.com] (Arabic)
* [http://hailoosport.com/league?comp_id=640f6eec53e8b4e3381f1f3a10a902dc&lang=en Syrian Premier League - Hailoosport.com]


{{Syrian football}}
{{Syrian League}}
{{Syrian Premier League seasons}}
{{AFC Leagues}}

[[Category:Syrian Premier League| ]]
[[Category:Top level football leagues in Asia|Syria]]
[[Category:Sports leagues established in 1966]]
[[Category:1966 establishments in Syria]]
------------


{{EngvarB|date=September 2013}}
{{Use dmy dates|date=September 2013}}
{{Good article}}
{{Infobox album <!-- See Wikipedia:WikiProject_Albums -->
| Name       = Parachutes
| Type       = studio
| Artist     = [[Coldplay]]
| Cover      = Coldplayparachutesalbumcover.jpg
| Released   = {{Start date|2000|07|10|df=yes}}
| Recorded   = November 1999 ??? May 2000
| Studio     = {{hlist|Matrix, London|[[Wessex Studios]], London|Parr Street, [[Liverpool]]|[[Rockfield Studios]], [[Rockfield, Monmouthshire|Rockfield]]}}
{{small|(Except "High Speed" recorded summer 1999 at [[Miloco Studios|Orinoco]], London)}}
| Genre      = {{hlist|[[Alternative rock]]|[[post-Britpop]]}}
| Length     = 41:44
| Label      = [[Parlophone]]
| Producer   = {{hlist|[[Ken Nelson (British record producer)|Ken Nelson]]|Coldplay|[[Chris Allison]] {{small|(track 8 only)}}}}
| Last album = ''[[The Blue Room (EP)|The Blue Room]]''<br>(1999)
| This album = '''''Parachutes'''''<br>(2000)
| Next album = ''[[Acoustic (Coldplay EP)|Acoustic EP]]''<br>(2000)
| Misc = {{Extra chronology
 | Artist     = [[Coldplay]] studio album
 | Type       = studio
 | Last album =
 | This album = '''''Parachutes'''''<br />(2000)
 | Next album = ''[[A Rush of Blood to the Head]]''<br />(2002)
 }}
 {{Singles
 | Name = Parachutes
 | Type = Studio
 | single 1 = [[Shiver (Coldplay song)|Shiver]]
 | single 1 date = 6 March 2000
 | single 2 = [[Yellow (Coldplay song)|Yellow]]
 | single 2 date = 26 June 2000
 | single 3 = [[Trouble (Coldplay song)|Trouble]]
 | single 3 date = 26 October 2000
 | single 4 = [[Don't Panic (song)|Don't Panic]]
 | single 4 date = 19 March 2001
 }}
}}

'''''Parachutes''''' is the debut [[studio album]] by British [[alternative rock]] band [[Coldplay]]. It was released by [[Parlophone]] on 10 July 2000 in the United Kingdom. The album was produced by the band and British record producer [[Ken Nelson (British record producer)|Ken Nelson]], excluding one track, "High Speed", which was produced by [[Chris Allison]]. ''Parachutes'' has spawned the hit singles "[[Shiver (Coldplay song)|Shiver]]", "[[Yellow (Coldplay song)|Yellow]]", "[[Trouble (Coldplay song)|Trouble]]", and "[[Don't Panic (song)|Don't Panic]]".

The album was a commercial success, and was met with positive reviews. Upon release, the album quickly reached number one in the United Kingdom, and has since been certified 8?? Platinum. In the United States, the album peaked at number 51 on the [[Billboard 200|''Billboard'' 200]], and has since been certified 2?? Platinum. It won the [[Grammy Award for Best Alternative Music Album]] in 2002, and has earned the band various accolades since its release. ''Parachutes'' is also the [[List of best-selling albums of the 2000s (century) in the United Kingdom|17th best-selling album of the 21st century in the United Kingdom]], and won the Best British Album award at the 2001 [[Brit Awards]]. As of 2011, it has sold around 8.5 million copies worldwide.

==Recording and production==
The band started working on the album in 1999 and produced an EP with British record producer [[Chris Allison]]. Allison was asked to 'come in and give the band a bit of a direction sound wise. Both the band and the A&R department ??? both parties wanted that'.<ref>Coldplay, Look at the Stars by Phil O'Brien. p35</ref> Things got off to a productive start with the song 'High Speed', which ultimately proved good enough to make it onto the Parachutes album. Allison describes it thus: 'You'll notice it is quite a bit different to the other tracks, because there are other sounds going on in it: we wanted to mix a soundscape in with the classic rock sound on that particular track. I thought 'High Speed' was a really good marriage between the classic rock sound and the new sound that was developing out of it, something that was more atmospheric'.<ref>Coldplay, Look at the Stars by Phil O'Brien. p36</ref> Seven tracks in all were recorded during the sessions at Orinoco studios in London, three of them ended up on ''[[The Blue Room (EP)|The Blue Room]]'' EP.

The band took a break to write more songs for the album. A few months later it was arranged that Allison and the band meet at a rehearsal room to start on the album proper. "They started up playing in the rehearsal room and they really weren't together at all. And I was very honest with them, I just sort of said 'Look this simply isn't good enough'". Allison adds, "The interesting, the most significant thing that did occur out of the fact that we didn't end up starting the album on that day of the rehearsal was that [[Chris Martin]] had not written 'Yellow' by that time".<ref>Coldplay, Look at the Stars by Phil O'Brien. p43</ref>

Several months later British record producer [[Ken Nelson (British record producer)|Ken Nelson]] was chosen, producing all but one song on ''Parachutes''. He was introduced to Coldplay by his manager Pete Byrne (who gave him a copy of the band's [[Fierce Panda Records|Fierce Panda]]-distributed [[Brothers & Sisters (song)|debut single]] in 1999). Nelson has claimed that, as soon as he heard vocalist Chris Martin's voice on the song "Bigger Stronger", he "realised that he was something special". Nelson was offered the job while Coldplay were performing in Liverpool with English [[indie rock]] band [[Gomez (band)|Gomez]] (whose debut album, ''[[Bring It On (Gomez album)|Bring It On]]'', was what he had produced at the time).<ref name="Inglis">{{cite web|url=http://www.soundonsound.com/sos/oct00/articles/ken.htm|title=Recording Coldplay's Parachutes|last=Inglis|first=Sam|date=October 2000|work=SOS|accessdate=9 September 2008}}</ref>

Coldplay initially planned to record ''Parachutes'' in the space of two weeks. However, tours and other live performances caused the recording to spread out between September 1999 and April???May 2000.<ref name="Roach45">Roach, p. 45</ref> The band began work on the album at [[Rockfield Studios]] in Wales, Matrix Studios, and [[Wessex Sound Studios]], although the majority of ''Parachutes''{{'}} tracks were recorded at [[Liverpool]]'s Parr Street Studios. The band worked in three studio rooms at Parr Street, and tracked much of the album in one of these rooms???the project studio which producer Ken Nelson describes as "basically a demo room". The Chris Allison-produced track "High Speed" was also included on the album, and originates from earlier sessions at Orinico Studios in London. The album was [[Audio mixing (recorded music)|mixed]] by American engineer [[Michael Brauer]] in New York. Coldplay's record label, [[Parlophone]], had originally intended to use a mixing engineer for the tracks they picked as singles, but eventually hired Brauer to work on all songs on ''Parachutes''<ref name="Inglis" /> except the song "High Speed" which was mixed by Chris Allison.

At the Liverpool concert where he was offered the production job Nelson had noted that Coldplay's performance was "very very uptight [...] they rushed through the set and it was quite difficult to listen to". Once in the studio Nelson and the band went through each song, learning how to play the piece live and deciding what tempo to play it at in an attempt to get the group to "calm down" ("[[Trouble (Coldplay song)|Trouble]]", for example, had to be reworked to eliminate the [[cacophony]] included in its early versions).<ref name="Inglis" />

The album's cover features a photograph of a [[globe]] taken with a disposable [[Kodak]] camera. The globe had been purchased from [[W H Smith]] for [[Pound (currency)|??]]10; it was featured in the music videos for "[[Shiver (Coldplay song)|Shiver]]" and "[[Don't Panic (song)|Don't Panic]]", and also accompanied the band on their tours.<ref name="Roach36">Roach, p. 36</ref> The album was dedicated to drummer [[Will Champion]]'s mother, Dr. Sara Champion, who died of cancer in 2000.<ref>(2000) Artwork for ''Parachutes'' by Coldplay. Capitol (0 6700 30162 2 3).</ref>

==Music and style==
[[File:Coldplay - Don't Panic.jpg|thumb|Coldplay performing "Yellow" in the 2005 [[Twisted Logic Tour]].]]

Champion has explained that Nelson's production style was liberating and allowed the band to feel at ease during the recording of ''Parachutes'' (many songs from the album often featured slow tempos). The ensuing album was "a record's worth of moody and atmospheric tunes". As a nod to the moods created by the album, Champion has compared the song lyrics to the 1972 song "[[Perfect Day (Lou Reed song)|Perfect Day]]" by American rock singer-songwriter [[Lou Reed]], stating that the "lyrics are beautiful and they're really, really happy, but the music is really, really sad. It's that kind of thing, where you can create [differing] moods through the music and lyrics."<ref>{{cite news|url=http://www.mtv.com/news/articles/1427213/20000929/coldplay.jhtml|title=Coldplay Opens Up "Parachutes" For U.S. Audiences|last=Basham|first=David|date=29 September 2000|publisher=MTV|accessdate=14 September 2008}}</ref>

''Parachutes'' was recognised to have an [[alternative rock]] sound similar to English band [[Radiohead]] in their ''[[The Bends|Bends]]'' era. In fact, it has been suggested that the album's commercial success was due in part to a portion of Radiohead's audience being alienated by the band's experimental and more electronic-influenced ''[[Kid A]]'' album.<ref>{{cite news|url=http://www.2walls.com/REVIEWS/MUSIC/coldplay.asp|title=Coldplay: Parachutes|last=Finch|first=Stephan|date=16 February 2001|publisher= 2 Walls Webzine|accessdate=15 September 2008}}</ref>

==Release and promotion==
''Parachutes'' was released on 10 July 2000 in the United Kingdom via record label Parlophone. In the United States, it was released on 7 November 2000 by record label Nettwerk.<ref>{{cite news|url=http://www.billboard.com/bbcom/search/google/article_display.jsp?vnu_content_id=874414|title=Nettwerk To Release Coldplay Album|last=Cohen|first=Jonathan|date=2 August 2000|work=Billboard|publisher=Nielsen Business Media, Inc|accessdate=15 September 2008}}</ref> The album has been made available on various formats since its initial release; both Parlophone and Nettwerk released it as a CD in 2000, and it was also released as a [[Compact Cassette|cassette]] by newfound US label [[Capitol Records|Capitol]] in 2001. In the following year, Parlophone issued the album as an [[LP album|LP]].<ref>{{cite web|url={{BillboardURLbyName|artist=coldplay|chart=all}} |title=Discography ??? Coldplay: Parachutes |work=Billboard |publisher=Nielsen Business Media, Inc |accessdate=30 September 2008 |deadurl=yes |archiveurl=http://web.archive.org/web/20100106020206/{{BillboardURLbyName|artist=coldplay|chart=Billboard 200}} |archivedate=6 January 2010 }}</ref>

The main version of the album contains 10 tracks; the tenth track, "Everything's Not Lost", segues to a hidden short track called "Life Is for Living", clocking in for a total of 7:15. The Japanese version of the album contains all main tracks, and the additional tracks "Careful Where You Stand" and "For You".

Four singles were released from the album: "Shiver", "[[Yellow (Coldplay song)|Yellow]]", "Trouble", and "Don't Panic". "Shiver" served as [[lead single]] in the United Kingdom while "Yellow" was used in the United States. Upon the release of "Trouble", Coldplay abandoned their initial plan of releasing "Don't Panic" as the album's fourth single, after they deemed three singles were enough for an album. Despite this, however, it was released as a single in some European regions.<ref name="Roach54">Roach, p. 54</ref>

Since its wide release, ''Parachutes'' has earned the band a large array of awards. The album won Best Album at the 2000 ''[[Q (magazine)|Q]]'' Awards, and was nominated at the 2000 [[Mercury Music Prize]]. The following year, the band earned [[Grammy Award for Best Alternative Music Album|Best Alternative Music Album]] at the [[Grammy Award]]s and Best British Album at the [[BRIT Awards]].<ref>{{cite web|url=http://www.grammy.com/GRAMMY_Awards/Winners/Results.aspx?title=&winner=Coldplay&year=0&genreID=0&hp=1 |title=Grammy Awards Winners |publisher=The Recording Academy |accessdate=15 September 2008 |deadurl=yes |archiveurl=https://web.archive.org/20080525233829/http://www.grammy.com:80/GRAMMY_Awards/Winners/Results.aspx?title=&winner=Coldplay&year=0&genreID=0&hp=1 |archivedate=25 May 2008 }}</ref><ref>{{cite news|url=http://www.mtv.com/news/articles/1440978/20010226/williams_robbie.jhtml|title=Robbie Williams, U2, Coldplay Dominate Brit Awards|last=Kemp|first=Rob|date=26 February 2001|publisher=MTV|accessdate=15 September 2008}}</ref>

==Critical reception==
{{Album reviews
| rev1 = [[AllMusic]]
| rev1Score = {{Rating|4|5}}<ref name="Allmusic">{{cite web |url=http://www.allmusic.com/album/parachutes-mw0000101998 |title=Parachutes ??? Coldplay |publisher=[[AllMusic]] |accessdate=25 November 2010 |last=Wilson |first=MacKenzie}}</ref>
| rev2 = ''[[Alternative Press]]''
| rev2Score = 4/5<ref>{{cite journal |title=Coldplay: Parachutes |work=[[Alternative Press]] |issue=149 |date=December 2000 |page=94}}</ref>
| rev3 = ''[[Encyclopedia of Popular Music]]''

In [42]:
from pyspark.ml.feature import (
    IDF,
    HashingTF,
    Normalizer,
    RegexTokenizer,
    StopWordsRemover,
)

##### Step 1: Natural Language Processing: RegexTokenizer: Convert the lowerText col to a bag of words

In [43]:
tokenizer = RegexTokenizer().setInputCol("text").setOutputCol("words").setPattern(r"\W+")

In [44]:
wiki_words_df = tokenizer.transform(wiki_df)

In [45]:
wiki_words_df.printSchema()

root
 |-- id: long (nullable = true)
 |-- title: string (nullable = true)
 |-- lastrev_pdt_time: timestamp (nullable = true)
 |-- revid: long (nullable = true)
 |-- comment: string (nullable = true)
 |-- contributorid: long (nullable = true)
 |-- contributorusername: string (nullable = true)
 |-- contributorip: string (nullable = true)
 |-- text: string (nullable = true)
 |-- words: array (nullable = true)
 |    |-- element: string (containsNull = true)

In [46]:
np.array(wiki_words_df.select("words").first()[0])

array(['infobox', 'football', 'league', 'logo', 'pixels', 'country',
       'syria', 'confed', 'afc', 'founded', '1966', 'teams', '20',
       'relegation', '2', 'syrian', 'league', 'levels', '1', 'domest_cup',
       'syrian', 'cup', 'br', 'syrian', 'super', 'cup', 'confed_cup',
       'afc', 'cup', 'br', 'arab', 'champions', 'league', 'champions',
       'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', 'season', '2014',
       '15', 'most', 'successful', 'club', 'al', 'jaish', 'sc',
       'damascus', 'al', 'jaish', '13', 'titles', 'website', 'current',
       '2015', '16', 'syrian', 'premier', 'league', 'the', 'syrian',
       'league', 'is', 'the', 'highest', 'division', 'in', 'association',
       'football', 'football', 'in', 'syria', 'the', 'league', 'began',
       'to', 'play', 'in', '1966', 'current', 'clubs', '2015', '16',
       'group', '1', 'al', 'hurriya', 'sc', 'al', 'hurriya', 'aleppo',
       'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', 'damascus', 'al',
       'jazeera', 'sc', 'hasakah', 'al', 'jazeera', 'hasakah', 'al',
       'karamah', 'sc', 'al', 'karamah', 'homs', 'al', 'majd', 'sc', 'al',
       'majd', 'damascus', 'al', 'muhafaza', 'sc', 'al', 'muhafaza',
       'damascus', 'taliya', 'sc', 'al', 'taliya', 'hama', 'hutteen',
       'sc', 'hutteen', 'latakia', 'jableh', 'sc', 'jableh', 'jableh',
       'omayya', 'sc', 'omayya', 'idlib', 'group', '2', 'al', 'ittihad',
       'sc', 'aleppo', 'al', 'ittihad', 'aleppo', 'al', 'fotuwa', 'sc',
       'al', 'futowa', 'deir', 'ez', 'zor', 'al', 'jihad', 'sc', 'al',
       'jihad', 'relegated', 'qamishli', 'nawair', 'sc', 'al', 'nawair',
       'hama', 'nidal', 'sc', 'al', 'nidal', 'damascus', 'al', 'shorta',
       'sc', 'damascus', 'al', 'shorta', 'damascus', 'al', 'wahda', 'sc',
       'damascus', 'al', 'wahda', 'damascus', 'al', 'wathba', 'sc', 'al',
       'wathba', 'homs', 'baniyas', 'refinery', 'sc', 'musfat', 'baniyas',
       'baniyas', 'tishreen', 'sc', 'tishreen', 'latakia', 'list', 'of',
       'champions', 'champions', 'so', 'far', 'are', 'ref', 'cite', 'web',
       'url', 'http', 'www', 'rsssf', 'com', 'tabless', 'syrchamp',
       'html', 'publisher', 'rsssf', 'accessdate', '6', 'july', '2012',
       'title', 'syria', 'list', 'of', 'champions', 'ref', 'class',
       'wikitable', 'style', 'width', '55', 'style', 'width', '10',
       'season', 'style', 'width', '15', 'winner', 'style', 'width', '15',
       'runner', 'up', 'style', 'width', '15', 'third', 'place', '1966',
       '67', 'al', 'ittihad', 'sc', 'aleppo', 'al', 'ittihad', '1967',
       '68', 'al', 'ittihad', 'sc', 'aleppo', 'al', 'ittihad', '1968',
       '69', 'barada', 'sc', 'barada', '1969', '70', 'barada', 'sc',
       'barada', '1970', '71', 'colspan', '3', 'style', 'background',
       'efefef', 'center', 'no', 'championship', '1971', '72', 'colspan',
       '3', 'style', 'background', 'efefef', 'center', 'no',
       'championship', '1972', '73', 'al', 'jaish', 'sc', 'damascus',
       'al', 'jaish', '1973', '74', 'colspan', '3', 'style', 'background',
       'efefef', 'center', 'no', 'championship', '1974', '75', 'al',
       'karamah', 'sc', 'al', 'karamah', '1975', '76', 'al', 'jaish',
       'sc', 'damascus', 'al', 'jaish', '1976', '77', 'al', 'ittihad',
       'sc', 'aleppo', 'al', 'ittihad', '1977', '78', 'colspan', '3',
       'style', 'background', 'efefef', 'center', 'no', 'championship',
       '1978', '79', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish',
       '1979', '80', 'al', 'shorta', 'sc', 'damascus', 'al', 'shorta',
       '1980', '81', 'colspan', '3', 'style', 'background', 'efefef',
       'center', 'no', 'championship', '1981', '82', 'tishreen', 'sc',
       'tishreen', '1982', '83', 'al', 'karamah', 'sc', 'al', 'karamah',
       '1983', '84', 'al', 'karamah', 'sc', 'al', 'karamah', '1984', '85',
       'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '1985', '86', 'al',
       'jaish', 'sc', 'damascus', 'al', 'jaish', '1986', '87', 'jableh',
       'sc', 'jableh', '1987', '88', 'jableh', 'sc', 'jableh', '1988',
       '89', 'jableh', 'sc', 'jableh', '1989', '90', 'al', 'fotuwa', 'sc',
       'al', 'futowa', '1990', '91', 'al', 'fotuwa', 'sc', 'al', 'futowa',
       '1991', '92', 'hurriya', 'sc', 'hurriya', '1992', '93', 'al',
       'ittihad', 'sc', 'aleppo', 'al', 'ittihad', '1993', '94',
       'hurriya', 'sc', 'hurriya', '1994', '95', 'al', 'ittihad', 'sc',
       'aleppo', 'al', 'ittihad', '1995', '96', 'al', 'karamah', 'sc',
       'al', 'karamah', '1996', '97', 'tishreen', 'sc', 'tishreen',
       '1997', '98', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish',
       '1998', '99', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish',
       '1999', '00', 'jableh', 'sc', 'jableh', '2000', '01', 'al',
       'jaish', 'sc', 'damascus', 'al', 'jaish', '2001', '02', 'al',
       'jaish', 'sc', 'damascus', 'al', 'jaish', '2002', '03', 'al',
       'jaish', 'sc', 'damascus', 'al', 'jaish', '2003', '04', 'al',
       'wahda', 'sc', 'damascus', 'al', 'wahda', '2004', '05', 'al',
       'ittihad', 'sc', 'aleppo', 'al', 'ittihad', '2005', '06', 'al',
       'karamah', 'sc', 'al', 'karamah', '2006', '07', 'al', 'karamah',
       'sc', 'al', 'karamah', '2007', '08', 'syrian', 'premier', 'league',
       '2007', '08', 'al', 'karamah', 'sc', 'al', 'karamah', '2008', '09',
       'syrian', 'premier', 'league', '2008', '09', 'al', 'karamah', 'sc',
       'al', 'karamah', '2009', '10', 'syrian', 'premier', 'league',
       '2009', '10', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish',
       '2010', '11', 'syrian', 'premier', 'league', '2010', '11',
       'colspan', '3', 'style', 'background', 'efefef', 'center',
       'suspended', '2011', '12', 'syrian', 'premier', 'league', '2011',
       '12', 'al', 'shorta', 'sc', 'damascus', 'al', 'shorta', '2013',
       'syrian', 'premier', 'league', '2013', 'al', 'jaish', 'sc',
       'damascus', 'al', 'jaish', '2014', 'syrian', 'premier', 'league',
       '2014', 'al', 'wahda', 'sc', 'damascus', 'al', 'wahda', '2014',
       '15', 'syrian', 'premier', 'league', '2014', '15', 'al', 'jaish',
       'sc', 'damascus', 'al', 'jaish', 'performances', 'performance',
       'by', 'club', 'class', 'wikitable', 'sortable', 'style', 'width',
       '100', 'style', 'width', '15', 'club', 'style', 'width', '10',
       'winners', 'style', 'width', '10', 'runners', 'up', 'style',
       'width', '10', 'third', 'place', 'style', 'width', '55', 'winning',
       'years', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', 'center',
       '13', 'center', '4', 'center', '1', 'al', 'karamah', 'sc', 'al',
       'karamah', 'center', '8', 'center', '11', 'center', '4', 'al',
       'ittihad', 'sc', 'aleppo', 'al', 'ittihad', 'center', '6',
       'center', '6', 'center', '12', 'jableh', 'sc', 'jableh', 'center',
       '4', 'center', '6', 'center', '1', 'al', 'shorta', 'sc',
       'damascus', 'al', 'shorta', 'center', '2', 'center', '6', 'center',
       '2', 'al', 'fotuwa', 'sc', 'al', 'futowa', 'center', '2', 'center',
       '5', 'center', '3', 'hurriya', 'sc', 'al', 'hurriya', 'center',
       '2', 'center', '1', 'center', '3', 'al', 'wahda', 'sc', 'damascus',
       'al', 'wahda', 'center', '2', 'center', 'center', '5', 'tishreen',
       'sc', 'tishreen', 'center', '2', 'center', 'center', '4', 'barada',
       'sc', 'barada', 'center', '2', 'center', 'center', '2',
       'performance', 'by', 'city', 'class', 'wikitable', 'sortable',
       'width', '120', 'list', 'of', 'cities', 'in', 'syria', 'city',
       'width', '10', 'winners', 'width', '150', 'club', 's', 'see',
       'also', 'syrian', 'premier', 'league', 'top', 'scorers',
       'references', 'reflist', 'external', 'links', 'http', 'www',
       'fifa', 'com', 'associations', 'association', 'syr',
       'nationalleague', 'standings', 'html', 'league', 'at', 'fifa',
       'http', 'www', 'soccerway', 'com', 'national', 'syria', 'league',
       'at', 'soccerway', 'com', 'http', 'hailoosport', 'com', 'league',
       'lang', 'ar', 'comp_id', '640f6eec53e8b4e3381f1f3a10a902dc',
       'syrian', 'premier', 'league', 'hailoosport', 'com', 'arabic',
       'http', 'hailoosport', 'com', 'league', 'comp_id',
       '640f6eec53e8b4e3381f1f3a10a902dc', 'lang', 'en', 'syrian',
       'premier', 'league', 'hailoosport', 'com', 'syrian', 'football',
       'syrian', 'league', 'syrian', 'premier', 'league', 'seasons',
       'afc', 'leagues', 'category', 'syrian', 'premier', 'league',
       'category', 'top', 'level', 'football', 'leagues', 'in', 'asia',
       'syria', 'category', 'sports', 'leagues', 'established', 'in',
       '1966', 'category', '1966', 'establishments', 'in', 'syria'],
      dtype='<U32')

##### Step 2: Natural Language Processing: StopWordsRemover: Remove Stop words

In [47]:
remover = StopWordsRemover().setInputCol("words").setOutputCol("noStopWords")

In [48]:
no_stop_words_list_df = remover.transform(wiki_words_df)

In [49]:
no_stop_words_list_df.printSchema()

root
 |-- id: long (nullable = true)
 |-- title: string (nullable = true)
 |-- lastrev_pdt_time: timestamp (nullable = true)
 |-- revid: long (nullable = true)
 |-- comment: string (nullable = true)
 |-- contributorid: long (nullable = true)
 |-- contributorusername: string (nullable = true)
 |-- contributorip: string (nullable = true)
 |-- text: string (nullable = true)
 |-- words: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- noStopWords: array (nullable = true)
 |    |-- element: string (containsNull = true)

In [50]:
no_stop_words_list_df.select("id", "title", "words", "noStopWords").show(15)

+--------+--------------------+--------------------+--------------------+
|      id|               title|               words|         noStopWords|
+--------+--------------------+--------------------+--------------------+
| 7523301|Syrian Premier Le...|[infobox, footbal...|[infobox, footbal...|
|  503927|  Parachutes (album)|[engvarb, date, s...|[engvarb, date, s...|
|12418406|Vinous-breasted s...|[taxobox, name, v...|[taxobox, name, v...|
|41099217|Newcastle upon Ty...|[the, newcastle, ...|[newcastle, upon,...|
| 6024369|        Tim Stoddard|[blp, sources, da...|[blp, sources, da...|
| 8040205|O come, O come, E...|[o, come, o, come...|[o, come, o, come...|
| 5870652|          Sal Butera|[use, mdy, dates,...|[use, mdy, dates,...|
| 6189968|          Jake Gibbs|[infobox, basebal...|[infobox, basebal...|
|   16341|     John Paul Jones|[about, the, led,...|[led, zeppelin, m...|
|  136920| Medford, New Jersey|[infobox, settlem...|[infobox, settlem...|
| 5760716|Christian Birmingham|[christian, birmi...|[christian, birmi...|
|   51390|                2018|[use, mdy, dates,...|[use, mdy, dates,...|
| 2407641|Raymond Wong Yuk-man|[other, people, r...|[people, raymond,...|
| 2856816|          Peary Land|[file, pearyland,...|[file, pearyland,...|
|28855673|      Bashkim Kadrii|[use, dmy, dates,...|[use, dmy, dates,...|
+--------+--------------------+--------------------+--------------------+
only showing top 15 rows

In [51]:
no_stop_words_list_df.select(F.explode("noStopWords").alias("words")).select(
    F.countDistinct("words")
).show()

+---------------------+
|count(DISTINCT words)|
+---------------------+
|              3720161|
+---------------------+

##### Step 3: HashingTF

![](img/tf-idf.png)

[*HashingTF*](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) es una técnica empleada para no tener que calcular la matriz *term frequency* completa, por métodos de hashing conseguimos resultados muy cercanos con una *performance* de cálculo mucho más rápida y paralelizable.

In [52]:
hashing_tf = HashingTF().setInputCol("noStopWords").setOutputCol("hashingTF").setNumFeatures(20000)

In [53]:
featurized_data_df = hashing_tf.transform(no_stop_words_list_df)

In [54]:
featurized_data_df.printSchema()

root
 |-- id: long (nullable = true)
 |-- title: string (nullable = true)
 |-- lastrev_pdt_time: timestamp (nullable = true)
 |-- revid: long (nullable = true)
 |-- comment: string (nullable = true)
 |-- contributorid: long (nullable = true)
 |-- contributorusername: string (nullable = true)
 |-- contributorip: string (nullable = true)
 |-- text: string (nullable = true)
 |-- words: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- noStopWords: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- hashingTF: vector (nullable = true)

In [55]:
featurized_data_df.select("id", "title", "noStopWords", "hashingTF").limit(10).toPandas()

,id,title,noStopWords,hashingTF
0,7523301,Syrian Premier League,"[infobox, football, league, logo, pixels, coun...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,503927,Parachutes (album),"[engvarb, date, september, 2013, use, dmy, dat...","(0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ..."
2,12418406,Vinous-breasted sparrowhawk,"[taxobox, name, vinous, breasted, sparrowhawk,...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,41099217,"Newcastle upon Tyne West by-election, 1940","[newcastle, upon, tyne, west, uk, parliament, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,6024369,Tim Stoddard,"[blp, sources, date, january, 2008, infobox, b...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
5,8040205,"O come, O come, Emmanuel","[o, come, o, come, emmanuel, christian, hymn, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
6,5870652,Sal Butera,"[use, mdy, dates, date, july, 2014, infobox, b...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
7,6189968,Jake Gibbs,"[infobox, baseball, biography, name, jake, gib...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
8,16341,John Paul Jones,"[led, zeppelin, musician, john, paul, jones, m...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
9,136920,"Medford, New Jersey","[infobox, settlement, name, medford, new, jers...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [56]:
vector = featurized_data_df.select("hashingTF").first()[0]

In [57]:
type(vector)

pyspark.ml.linalg.SparseVector

In [58]:
vector.values

array([  1.,   1.,   1.,   1.,   2.,   1.,   1.,   1.,   1.,   1.,   5.,
        34.,   1.,   1.,   3.,   1.,   1.,   1.,   1.,   2.,   2.,   1.,
         1.,   1.,   1.,   1.,   2.,   1.,   1.,   5.,   7.,   1.,   1.,
         4.,   2.,   1.,   2., 110.,   3.,   1.,   1.,   1.,   2.,   2.,
         1.,   8.,   1.,   8.,   1.,   2.,   1.,   4.,   1.,   2.,   1.,
         1.,   6.,   4.,   2.,   1.,   7.,   1.,   2.,   1.,   1.,   2.,
         2.,   5.,   1.,   5.,   1.,   1.,   1.,   2.,   2.,   1.,   1.,
         2.,   6.,   1.,  20.,   8.,   1.,   1.,   1.,   1.,  16.,   5.,
         1.,   2.,   1.,   1.,   1.,  14.,   1.,   1.,   2.,   7.,  14.,
         1.,  17.,   2.,   1.,   1.,   2.,   1.,   2.,   1.,   1.,   1.,
         1.,   2.,   2.,   1.,   1.,   1.,   4.,   1.,   2.,   2.,   1.,
         1.,   2.,   1.,   1.,   1.,   1.,   1.,   3.,   1.,   1.,   1.,
         1.,   1.,   5.,   1.,   8.,   1.,   1.,   2.,   1.,  36.,   1.,
         2.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   8.,   2.,   1.,
         6.,   1.,   1.,   1.,   1.,   1.,   2.,   3.,   1.,   2.,   1.,
         8.,   1.,   1.,   1.,   5.,   1.,   1.,   3.,   1.,   1.,   1.,
         1.,  10.,   6.,  24.,   2.,   1.,   2.,   1.,   2.,   4.,   1.,
         3.,  20.,   1.,   2.,   1.,   3.,   2.,   1.,   1.,   1.,   1.,
         2.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   4.,   1.,
         1.,  31.,   2.,   1.,   2.,   2.,   1.,   2.,   1.,   1.,   1.,
         1.,   1.,  13.,   5.,  10.,   1.,   1.,   3.,   1.,   2.,   1.,
         3.,   2.,   1.,   1.,   3.,   2.,   3.,   2.,   1.,   2.,   1.,
         1.,   1.,  75.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [59]:
vector.toArray()

array([0., 0., 0., ..., 0., 0., 0.])

In [60]:
aux = featurized_data_df.select("id", "title", "noStopWords", "hashingTF").first()

In [61]:
aux

Row(id=7523301, title='Syrian Premier League', noStopWords=['infobox', 'football', 'league', 'logo', 'pixels', 'country', 'syria', 'confed', 'afc', 'founded', '1966', 'teams', '20', 'relegation', '2', 'syrian', 'league', 'levels', '1', 'domest_cup', 'syrian', 'cup', 'br', 'syrian', 'super', 'cup', 'confed_cup', 'afc', 'cup', 'br', 'arab', 'champions', 'league', 'champions', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', 'season', '2014', '15', 'successful', 'club', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '13', 'titles', 'website', 'current', '2015', '16', 'syrian', 'premier', 'league', 'syrian', 'league', 'highest', 'division', 'association', 'football', 'football', 'syria', 'league', 'began', 'play', '1966', 'current', 'clubs', '2015', '16', 'group', '1', 'al', 'hurriya', 'sc', 'al', 'hurriya', 'aleppo', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', 'damascus', 'al', 'jazeera', 'sc', 'hasakah', 'al', 'jazeera', 'hasakah', 'al', 'karamah', 'sc', 'al', 'karamah', 'homs', 'al', 'majd', 'sc', 'al', 'majd', 'damascus', 'al', 'muhafaza', 'sc', 'al', 'muhafaza', 'damascus', 'taliya', 'sc', 'al', 'taliya', 'hama', 'hutteen', 'sc', 'hutteen', 'latakia', 'jableh', 'sc', 'jableh', 'jableh', 'omayya', 'sc', 'omayya', 'idlib', 'group', '2', 'al', 'ittihad', 'sc', 'aleppo', 'al', 'ittihad', 'aleppo', 'al', 'fotuwa', 'sc', 'al', 'futowa', 'deir', 'ez', 'zor', 'al', 'jihad', 'sc', 'al', 'jihad', 'relegated', 'qamishli', 'nawair', 'sc', 'al', 'nawair', 'hama', 'nidal', 'sc', 'al', 'nidal', 'damascus', 'al', 'shorta', 'sc', 'damascus', 'al', 'shorta', 'damascus', 'al', 'wahda', 'sc', 'damascus', 'al', 'wahda', 'damascus', 'al', 'wathba', 'sc', 'al', 'wathba', 'homs', 'baniyas', 'refinery', 'sc', 'musfat', 'baniyas', 'baniyas', 'tishreen', 'sc', 'tishreen', 'latakia', 'list', 'champions', 'champions', 'far', 'ref', 'cite', 'web', 'url', 'http', 'www', 'rsssf', 'com', 'tabless', 'syrchamp', 'html', 'publisher', 'rsssf', 'accessdate', '6', 'july', '2012', 'title', 'syria', 'list', 'champions', 'ref', 'class', 'wikitable', 'style', 'width', '55', 'style', 'width', '10', 'season', 'style', 'width', '15', 'winner', 'style', 'width', '15', 'runner', 'style', 'width', '15', 'third', 'place', '1966', '67', 'al', 'ittihad', 'sc', 'aleppo', 'al', 'ittihad', '1967', '68', 'al', 'ittihad', 'sc', 'aleppo', 'al', 'ittihad', '1968', '69', 'barada', 'sc', 'barada', '1969', '70', 'barada', 'sc', 'barada', '1970', '71', 'colspan', '3', 'style', 'background', 'efefef', 'center', 'championship', '1971', '72', 'colspan', '3', 'style', 'background', 'efefef', 'center', 'championship', '1972', '73', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '1973', '74', 'colspan', '3', 'style', 'background', 'efefef', 'center', 'championship', '1974', '75', 'al', 'karamah', 'sc', 'al', 'karamah', '1975', '76', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '1976', '77', 'al', 'ittihad', 'sc', 'aleppo', 'al', 'ittihad', '1977', '78', 'colspan', '3', 'style', 'background', 'efefef', 'center', 'championship', '1978', '79', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '1979', '80', 'al', 'shorta', 'sc', 'damascus', 'al', 'shorta', '1980', '81', 'colspan', '3', 'style', 'background', 'efefef', 'center', 'championship', '1981', '82', 'tishreen', 'sc', 'tishreen', '1982', '83', 'al', 'karamah', 'sc', 'al', 'karamah', '1983', '84', 'al', 'karamah', 'sc', 'al', 'karamah', '1984', '85', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '1985', '86', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '1986', '87', 'jableh', 'sc', 'jableh', '1987', '88', 'jableh', 'sc', 'jableh', '1988', '89', 'jableh', 'sc', 'jableh', '1989', '90', 'al', 'fotuwa', 'sc', 'al', 'futowa', '1990', '91', 'al', 'fotuwa', 'sc', 'al', 'futowa', '1991', '92', 'hurriya', 'sc', 'hurriya', '1992', '93', 'al', 'ittihad', 'sc', 'aleppo', 'al', 'ittihad', '1993', '94', 'hurriya', 'sc', 'hurriya', '1994', '95', 'al', 'ittihad', 'sc', 'aleppo', 'al', 'ittihad', '1995', '96', 'al', 'karamah', 'sc', 'al', 'karamah', '1996', '97', 'tishreen', 'sc', 'tishreen', '1997', '98', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '1998', '99', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '1999', '00', 'jableh', 'sc', 'jableh', '2000', '01', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '2001', '02', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '2002', '03', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '2003', '04', 'al', 'wahda', 'sc', 'damascus', 'al', 'wahda', '2004', '05', 'al', 'ittihad', 'sc', 'aleppo', 'al', 'ittihad', '2005', '06', 'al', 'karamah', 'sc', 'al', 'karamah', '2006', '07', 'al', 'karamah', 'sc', 'al', 'karamah', '2007', '08', 'syrian', 'premier', 'league', '2007', '08', 'al', 'karamah', 'sc', 'al', 'karamah', '2008', '09', 'syrian', 'premier', 'league', '2008', '09', 'al', 'karamah', 'sc', 'al', 'karamah', '2009', '10', 'syrian', 'premier', 'league', '2009', '10', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '2010', '11', 'syrian', 'premier', 'league', '2010', '11', 'colspan', '3', 'style', 'background', 'efefef', 'center', 'suspended', '2011', '12', 'syrian', 'premier', 'league', '2011', '12', 'al', 'shorta', 'sc', 'damascus', 'al', 'shorta', '2013', 'syrian', 'premier', 'league', '2013', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', '2014', 'syrian', 'premier', 'league', '2014', 'al', 'wahda', 'sc', 'damascus', 'al', 'wahda', '2014', '15', 'syrian', 'premier', 'league', '2014', '15', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', 'performances', 'performance', 'club', 'class', 'wikitable', 'sortable', 'style', 'width', '100', 'style', 'width', '15', 'club', 'style', 'width', '10', 'winners', 'style', 'width', '10', 'runners', 'style', 'width', '10', 'third', 'place', 'style', 'width', '55', 'winning', 'years', 'al', 'jaish', 'sc', 'damascus', 'al', 'jaish', 'center', '13', 'center', '4', 'center', '1', 'al', 'karamah', 'sc', 'al', 'karamah', 'center', '8', 'center', '11', 'center', '4', 'al', 'ittihad', 'sc', 'aleppo', 'al', 'ittihad', 'center', '6', 'center', '6', 'center', '12', 'jableh', 'sc', 'jableh', 'center', '4', 'center', '6', 'center', '1', 'al', 'shorta', 'sc', 'damascus', 'al', 'shorta', 'center', '2', 'center', '6', 'center', '2', 'al', 'fotuwa', 'sc', 'al', 'futowa', 'center', '2', 'center', '5', 'center', '3', 'hurriya', 'sc', 'al', 'hurriya', 'center', '2', 'center', '1', 'center', '3', 'al', 'wahda', 'sc', 'damascus', 'al', 'wahda', 'center', '2', 'center', 'center', '5', 'tishreen', 'sc', 'tishreen', 'center', '2', 'center', 'center', '4', 'barada', 'sc', 'barada', 'center', '2', 'center', 'center', '2', 'performance', 'city', 'class', 'wikitable', 'sortable', 'width', '120', 'list', 'cities', 'syria', 'city', 'width', '10', 'winners', 'width', '150', 'club', 'see', 'also', 'syrian', 'premier', 'league', 'top', 'scorers', 'references', 'reflist', 'external', 'links', 'http', 'www', 'fifa', 'com', 'associations', 'association', 'syr', 'nationalleague', 'standings', 'html', 'league', 'fifa', 'http', 'www', 'soccerway', 'com', 'national', 'syria', 'league', 'soccerway', 'com', 'http', 'hailoosport', 'com', 'league', 'lang', 'ar', 'comp_id', '640f6eec53e8b4e3381f1f3a10a902dc', 'syrian', 'premier', 'league', 'hailoosport', 'com', 'arabic', 'http', 'hailoosport', 'com', 'league', 'comp_id', '640f6eec53e8b4e3381f1f3a10a902dc', 'lang', 'en', 'syrian', 'premier', 'league', 'hailoosport', 'com', 'syrian', 'football', 'syrian', 'league', 'syrian', 'premier', 'league', 'seasons', 'afc', 'leagues', 'category', 'syrian', 'premier', 'league', 'category', 'top', 'level', 'football', 'leagues', 'asia', 'syria', 'category', 'sports', 'leagues', 'established', '1966', 'category', '1966', 'establishments', 'syria'], hashingTF=SparseVector(20000, {130: 1.0, 348: 1.0, 397: 1.0, 403: 1.0, 458: 2.0, 592: 1.0, 648: 1.0, 649: 1.0, 667: 1.0, 1027: 1.0, 1228: 5.0, 1284: 34.0, 1499: 1.0, 1611: 1.0, 1637: 3.0, 1654: 1.0, 1685: 1.0, 1689: 1.0, 1993: 1.0, 2179: 2.0, 2183: 2.0, 2354: 1.0, 2405: 1.0, 2590: 1.0, 2602: 1.0, 2757: 1.0, 2758: 2.0, 2808: 1.0, 3094: 1.0, 3104: 5.0, 3174: 7.0, 3445: 1.0, 3469: 1.0, 3517: 4.0, 3560: 2.0, 3665: 1.0, 3683: 2.0, 3690: 110.0, 3710: 3.0, 3862: 1.0, 3939: 1.0, 3996: 1.0, 4007: 2.0, 4106: 2.0, 4186: 1.0, 4206: 8.0, 4224: 1.0, 4271: 8.0, 4279: 1.0, 4434: 2.0, 4574: 1.0, 4747: 4.0, 4901: 1.0, 4992: 2.0, 5056: 1.0, 5186: 1.0, 5266: 6.0, 5329: 4.0, 5551: 2.0, 5635: 1.0, 5641: 7.0, 5659: 1.0, 5693: 2.0, 5724: 1.0, 5755: 1.0, 5812: 2.0, 5919: 2.0, 5931: 5.0, 5950: 1.0, 5984: 5.0, 6113: 1.0, 6140: 1.0, 6220: 1.0, 6353: 2.0, 6390: 2.0, 6393: 1.0, 6394: 1.0, 6435: 2.0, 6478: 6.0, 6479: 1.0, 6499: 20.0, 6537: 8.0, 6559: 1.0, 7175: 1.0, 7180: 1.0, 7219: 1.0, 7293: 16.0, 7297: 5.0, 7351: 1.0, 7370: 2.0, 7417: 1.0, 7433: 1.0, 7509: 1.0, 7573: 14.0, 7709: 1.0, 7711: 1.0, 7741: 2.0, 7953: 7.0, 7956: 14.0, 7985: 1.0, 8000: 17.0, 8246: 2.0, 8257: 1.0, 8274: 1.0, 8342: 2.0, 8447: 1.0, 8626: 2.0, 8631: 1.0, 8661: 1.0, 9012: 1.0, 9048: 1.0, 9114: 2.0, 9191: 2.0, 9201: 1.0, 9261: 1.0, 9314: 1.0, 9330: 4.0, 9341: 1.0, 9351: 2.0, 9360: 2.0, 9470: 1.0, 9501: 1.0, 9569: 2.0, 9678: 1.0, 9810: 1.0, 9906: 1.0, 10132: 1.0, 10205: 1.0, 10263: 3.0, 10345: 1.0, 10458: 1.0, 10582: 1.0, 10586: 1.0, 10614: 1.0, 10665: 5.0, 10849: 1.0, 11072: 8.0, 11312: 1.0, 11317: 1.0, 11384: 2.0, 11433: 1.0, 11480: 36.0, 11521: 1.0, 11652: 2.0, 11685: 1.0, 11747: 1.0, 12079: 1.0, 12173: 1.0, 12206: 1.0, 12229: 1.0, 12334: 1.0, 12342: 8.0, 12358: 2.0, 12478: 1.0, 12490: 6.0, 12616: 1.0, 12620: 1.0, 12747: 1.0, 12758: 1.0, 13022: 1.0, 13055: 2.0, 13059: 3.0, 13083: 1.0, 13295: 2.0, 13417: 1.0, 13435: 8.0, 13515: 1.0, 13602: 1.0, 13628: 1.0, 13666: 5.0, 13792: 1.0, 13964: 1.0, 14007: 3.0, 14158: 1.0, 14349: 1.0, 14444: 1.0, 14620: 1.0, 14892: 10.0, 14961: 6.0, 14993: 24.0, 15083: 2.0, 15141: 1.0, 15204: 2.0, 15327: 1.0, 15328: 2.0, 15347: 4.0, 15354: 1.0, 15370: 3.0, 15433: 20.0, 15484: 1.0, 15495: 2.0, 15587: 1.0, 15644: 3.0, 15831: 2.0, 16093: 1.0, 16168: 1.0, 16284: 1.0, 16334: 1.0, 16339: 2.0, 16349: 1.0, 16365: 1.0, 16367: 1.0, 16500: 1.0, 16622: 1.0, 16646: 1.0, 16922: 1.0, 17148: 1.0, 17267: 4.0, 17333: 1.0, 17460: 1.0, 17468: 31.0, 17483: 2.0, 17691: 1.0, 17751: 2.0, 17766: 2.0, 17772: 1.0, 17819: 2.0, 17870: 1.0, 17910: 1.0, 18227: 1.0, 18250: 1.0, 18253: 1.0, 18323: 13.0, 18325: 5.0, 18381: 10.0, 18390: 1.0, 18408: 1.0, 18431: 3.0, 18442: 1.0, 18700: 2.0, 18722: 1.0, 18728: 3.0, 18771: 2.0, 18843: 1.0, 18952: 1.0, 19177: 3.0, 19189: 2.0, 19244: 3.0, 19309: 2.0, 19343: 1.0, 19371: 2.0, 19436: 1.0, 19478: 1.0, 19672: 1.0, 19680: 75.0, 19695: 1.0, 19764: 1.0, 19853: 1.0, 19857: 1.0, 19873: 1.0, 19914: 1.0, 19952: 1.0}))

##### Step 4: IDF

Calculamos ahora los puntuaciones inversas

In [62]:
idf = IDF().setInputCol("hashingTF").setOutputCol("idf")
idf_model = idf.fit(featurized_data_df)

In [63]:
idf_model

IDFModel: uid=IDF_6b6599bb6dd8, numDocs=111495, numFeatures=20000

In [64]:
idf_model.transform(featurized_data_df).select("text", "hashingTF", "idf").limit(10).toPandas()

,text,hashingTF,idf
0,{{Infobox football league\n| logo = \n| ...,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,{{EngvarB|date=September 2013}}\n{{Use dmy dat...,"(0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 3.8702686767778887, 0.0, ..."
2,{{Taxobox\n| name = Vinous-breasted sparrowhaw...,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,The '''[[Newcastle upon Tyne West (UK Parliame...,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,{{BLP sources|date=January 2008}}\n{{Infobox b...,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
5,"'''''O come, O come, Emmanuel''''' is a [[Chri...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
6,{{Use mdy dates|date=July 2014}}\n{{Infobox ba...,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
7,{{Infobox baseball biography\n|name=Jake Gibbs...,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
8,{{about||the Led Zeppelin musician|John Paul J...,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
9,{{Infobox settlement\n| name ...,"(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

##### Step 5: Normalizer

Cómo queremos usar un método que usa distancias (K-Means) suele ser aconsejable normalizar las variables de entrada para que su dimensión no altere en el resultado del algoritmo:

In [65]:
normalizer = Normalizer().setInputCol("idf").setOutputCol("features")

##### Step 6: k-means & tie it all together...

![](img/clustering.png)

In [66]:
from pyspark.ml import Pipeline
from pyspark.ml.clustering import KMeans

In [67]:
kmeans = KMeans().setFeaturesCol("features").setPredictionCol("prediction").setK(100).setSeed(1234)

In [68]:
pipeline = Pipeline(stages=[tokenizer, remover, hashing_tf, idf, normalizer, kmeans])

**CUIDADO** Este `fit` puede durar varios minutos:

In [69]:
model = pipeline.fit(wiki_df)

In [70]:
raw_predictions_df = model.transform(wiki_df).cache()

In [71]:
raw_predictions_df.count()

111495

En la variable `prediction` nos ha marcado en qué cluster a asignado cada artículo:

In [72]:
raw_predictions_df.select("prediction").limit(10).toPandas()

   prediction
0          31
1           5
2          31
3          32
4          50
5          31
6          50
7          50
8          29
9          39

¿Cuántos grupos hay?

In [73]:
raw_predictions_df.select("prediction").distinct().count()

100

In [74]:
raw_predictions_df.groupBy("prediction").count().orderBy(F.desc("count")).show(20)

+----------+-----+
|prediction|count|
+----------+-----+
|        31|37940|
|        33| 9575|
|         1| 5132|
|        77| 5125|
|        69| 4801|
|        85| 2965|
|        21| 2746|
|        29| 2746|
|        49| 2729|
|        62| 2631|
|         5| 2109|
|        32| 1909|
|        35| 1749|
|        39| 1727|
|        57| 1539|
|        42| 1467|
|         9| 1412|
|        30| 1243|
|        98| 1237|
|        88| 1100|
+----------+-----+
only showing top 20 rows

In [75]:
raw_predictions_df.filter(F.lower(F.col("title")).like("%hadoop%")).toPandas()

/opt/share/anaconda/lib/python3.11/site-packages/pyspark/sql/pandas/conversion.py:251: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

,id,title,lastrev_pdt_time,revid,comment,contributorid,contributorusername,contributorip,text,words,noStopWords,hashingTF,idf,features,prediction
0,5919308,Apache Hadoop,2016-03-04 22:58:48,708371306,/* History */,NaN,None,71.84.15.41,{{multiple issues|\n{{advert|date=October 2013...,"[multiple, issues, advert, date, october, 2013...","[multiple, issues, advert, date, october, 2013...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.371279522029...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0086322528147...",31

In [76]:
raw_predictions_df.filter(F.lower(F.col("title")).like("%apache spark%")).toPandas()

/opt/share/anaconda/lib/python3.11/site-packages/pyspark/sql/pandas/conversion.py:251: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  series = series.astype(t, copy=False)

,id,title,lastrev_pdt_time,revid,comment,contributorid,contributorusername,contributorip,text,words,noStopWords,hashingTF,idf,features,prediction
0,42164234,Apache Spark,2016-03-03 14:13:40,708135330,relegate details to footnotes,196471,Qwertyus,None,{{Infobox Software\n| name =...,"[infobox, software, name, apache, spark, logo,...","[infobox, software, name, apache, spark, logo,...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",31

In [77]:
raw_predictions_df.filter("prediction = 24").select("title").limit(20).toPandas()

                                            title
0                                     Mick Doohan
1              Mark Smith (British racing driver)
2                                   Wayne Gardner
3              Germany's Next Topmodel (cycle 11)
4   Independent Spirit Award for Best Female Lead
5                   Equipment of the Italian Army
6                List of Chief Ministers of Bihar
7                  Hell's Kitchen (U.S. season 5)
8                                  UE Sant Andreu
9                                        Tube map
10                                Mikhail Aleshin
11         Songs written and produced by R. Kelly
12                                 Nicol??s Terol
13                               Refrigerated van
14                  2015 NAIA men's soccer season
15                     1999 Formula Nippon season
16                  Himachal Pradesh cricket team
17          2000???01 Los Angeles Clippers season
18                                Life - Fear Not
19                      Bangladesh Premier League

Parece que la temática de estos artículos es informática / tecnología

In [78]:
spark.stop()